### PR TITLE
removing knob view from pedalRow

### PR DESCRIPTION
**Pull request by miggelucas**
As we agreed, removing knobs scrollview from pedalRow for a cleaner visualization of pedalList

### CODE REVIEW

**Review by matheusberger — CHANGES_REQUESTED** [review]
I think we still need to display the knob names, since the user has no "PedalDetailsView" to make sure the pedal was correctly created without going into the edit mode.

**Comment by matheusberger** [comment]
We should be able to click the pedal and go into a PedalDetailsView to check all the knobs and maybe also the Musics it was inserted into. I think this should be a future improvement for v2.0.

**Comment by miggelucas** [comment]
It makes sense to me. Gonna fix it right away.

**Review by matheusberger — APPROVED** [review]

**Review by matheusmigge — APPROVED** [review]
LGTM

**Pull request merged**
