### PR TITLE
Feature/pedal row swipe actions

### PR DESCRIPTION
**Pull request by miggelucas**
## What I have done

Features:
* Swipe action for CreatePedalView
    * Delete knob name
* Swipe action for HomeView
    * Delete Pedal
    * Edit Pedal
* HomeViewModel testing
* CreatePedalViewModel testing

### CODE REVIEW

**Review by matheusberger — CHANGES_REQUESTED** [review]
If you edit a pedal -> cancel -> tap create a pedal, the pedal creation screen comes up as the pedal edit screen for the pedal you first tried to edit. please fix this before merging.

**Comment by miggelucas** [comment]
Opa Homizaum! Good catch on that bug, it flew under my radar. Fixed it up and added a few more tests to make sure that glitch doesn't sneak back in. Cheers!

**Review by matheusmigge — APPROVED** [review]
LGTM

**Review by matheusberger — APPROVED** [review]
Thanks for fixing the bug, LGTM

**Pull request merged**
